### ISSUE TITLE
자기인증 API

### ISSUE THREAD

**Issue by 1J-Choi** [1J-Choi/MarkePost#3]
# 고려되는 방식

1. 카카오톡 / 네이버 인증서 본인인증
https://developers.barocert.com/
장점 : 가이드에 따라 쉽게 연동할 수 있음
단점: 테스트가 아닌 완벽한 기능을 위해서는 비용 지출 불가피가이드 대로 하는 것이기에 기능 추가라고 하기에 애매함유저가 카카오톡 or 네이버 인증서를 발급해야 해서 귀찮을 수 있음
 
2. 휴대폰 본인인증 (NICE API)
https://www.niceapi.co.kr/#/
장점: 가장 보편적이고 많이쓰는 방식단순해도 많이 쓰는 방식이기에 써본 경험이 강점이 될 수 있음
단점: 테스트도 지원 안하는 듯?쓰려면 무조건 상담 받고 지불 관련 등록 해야됨 돈돈돈~
 
3. 이메일 본인인증
https://green-bin.tistory.com/83
장점: 암호화된 코드를 db에 저장하고 코드를 메일로 보내주는 이해할 수 있는 구조의 방식요금도 들지 않음, 공지사항 메일이나 거래글 관련 메일과 같은 응용 가능
단점: 과연 이메일을 통한 본인인증이 적절한 방법일까? (일회용 이메일, 다계정의 이메일)
 
4. 카카오톡 메세지 본인인증
https://developers.kakao.com/docs/latest/ko/message/rest-api
장점: 이메일 보단 신뢰성이 높으면서이메일 보다 보편적이고 다른 기능으로의 활용성 높음
단점: 이메일 보다는 신뢰성이 있지만 완벽하진 않음 (카톡 다계정)

</body>
</html>

**Comment by 1J-Choi** [comment]
# 이메일 인증 구현 중의 어려움 

사용자의 거래 신뢰도를 확보하기 위해
본인인증 기능을 도입하고자 하였으며
이를 위해 채택한 방식은 바로 
이메일 본인인증 방식이였다.

이를 위해 선택한 이메일 전송 프로토콜은
Google SMTP이였다.

그러나 이메일 전송을 위해
Gmail에서 IMAP 사용 설정을 킨 뒤
기존에 나와있는 방법 대로 Google 계정에서
앱 비밀번호를 발급하려 했으나
해당 항목이 나오지 않았다.

때문에 찾아본 결과
권장되지 않는 방식이였기 때문에
해당 항목이 보이지 않도록 처리한 것이였다.

따라서 일단 Google 계정 고객 센터에 올라온
앱 비밀번호 등록 링크를 통해 우회하여
이를 발급하였으나 이후에 더 안전한 OAuth2를
사용한 방식으로 수정해볼 생각이 있다.

**Comment by 1J-Choi** [comment]
# 이메일 기능을 위한 환경설정

해당 기능을 구현하기 앞서
우선 프로젝트 내에 아래와 같은 의존성을 주입하였다.

```gradle
implementation 'org.springframework.boot:spring-boot-starter-mail'
```

이후 yml 파일 내에
이메일과 관련된 설정 내용을 작성하였는데
여기에는 구글 이메일과 앱 비밀번호가 들어갔기에
외부 yml 파일로 뺐으며 그 코드는 아래와 같다

```yml
# 파일명 application-mail.yml
spring:
  mail:
    host: smtp.gmail.com # SMTP 서버 주소 Google SMTP의 주소이다.
    username: chldnjswp110@gmail.com # 이메일
    password: zecx cacc wcwk szbo # Google 계정 설정에서 발급 받은 앱 비밀번
    properties:
      mail.smtp.auth: true # SMTP 인증 활성화 google SMTP 사용 시 필수적임
      mail.smtp.starttls.enable: true # SMTP 서버와의 통신에 TLS(Transport Layer Security) 암호화를 활성화 이 또한 Google SMTP에서 필수
```
